import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapPin, Search, Bell, ChevronDown, Star, Clock3, SlidersHorizontal, Navigation, CalendarDays, CarFront, Ticket, LayoutGrid, Heart, ArrowRight, Check, Plus, Zap, X, ShieldCheck, Sparkles} from 'lucide-react';
import './styles.css';

const washes = [
 {id:1,name:'Aqua Shine',area:'Yunusobod, 4-mavze',distance:'1.2 km',rating:'4.9',reviews:'128',price:'45 000',time:'08:00 – 22:00',tags:['Premium','24/7'],image:'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?auto=format&fit=crop&w=900&q=80',accent:'#0d817d'},
 {id:2,name:'ProWash Motors',area:'Mirzo Ulug‘bek ko‘chasi',distance:'2.4 km',rating:'4.8',reviews:'96',price:'35 000',time:'09:00 – 21:00',tags:['Tezkor','SUV'],image:'https://images.unsplash.com/photo-1565689876697-8c91f4f05052?auto=format&fit=crop&w=900&q=80',accent:'#ef9345'},
 {id:3,name:'Fresh Car',area:'Chilonzor, Bunyodkor',distance:'3.8 km',rating:'4.7',reviews:'74',price:'30 000',time:'08:30 – 20:00',tags:['Ekonom'],image:'https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?auto=format&fit=crop&w=900&q=80',accent:'#3f81bc'},
];
const times=['09:00','10:30','12:00','14:30','16:00','18:30'];

function Header({setPage}){return <header className="header"><div className="brand" onClick={()=>setPage('home')}><div className="logo"><span></span><span></span><span></span></div><b>Wash<span>Mee</span></b></div><nav><button className="active" onClick={()=>setPage('home')}>Bosh sahifa</button><button onClick={()=>setPage('explore')}>Avtomoykalar</button><button onClick={()=>setPage('bookings')}>Bronlarim</button></nav><div className="header-right"><button className="city"><MapPin size={16}/> Toshkent <ChevronDown size={14}/></button><button className="icon-btn"><Bell size={19}/><i></i></button><div className="avatar">AD</div><span className="username">Azizbek</span><ChevronDown size={15}/></div></header>}

function Hero({onExplore}){return <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse"></span> Toshkent bo‘ylab 48 ta avtomoyka</div><h1>Avtomoykani<br/><em>2 daqiqada</em> bron qiling.</h1><p>Navbat kutmang. O‘zingizga qulay avtomoykani toping, vaqtni tanlang va mashinangizni bemalol topshiring.</p><div className="hero-actions"><button className="primary" onClick={onExplore}>Avtomoyka topish <ArrowRight size={18}/></button><button className="ghost"><Zap size={17}/> Qanday ishlaydi?</button></div><div className="trust"><div className="faces"><span>AK</span><span>NS</span><span>DM</span></div><div><b>120+ haydovchi</b><small>allaqachon WashMee bilan</small></div></div></div><div className="hero-visual"><div className="map-bg"><div className="map-line l1"></div><div className="map-line l2"></div><div className="map-line l3"></div><div className="map-road r1"></div><div className="map-road r2"></div><div className="map-road r3"></div><div className="pin p1"><span></span></div><div className="pin p2"><span></span></div><div className="pin p3"><span></span></div><div className="main-pin"><MapPin fill="currentColor" size={28}/><label>Aqua Shine<br/><small>1.2 km</small></label></div><div className="mini-card"><div className="mini-icon"><Clock3 size={16}/></div><div><b>Bugun, 14:30</b><small>Bron qilishga tayyor</small></div><Check size={18} color="#0c817c"/></div></div></div></section>}

function WashCard({wash,onBook}){return <article className="wash-card"><div className="card-img"><img src={wash.image}/><button className="heart"><Heart size={17}/></button><div className="open">● Ochiq</div></div><div className="card-content"><div className="card-title"><div><h3>{wash.name}</h3><p><MapPin size={14}/> {wash.area} <span>· {wash.distance}</span></p></div><div className="rating"><Star size={14} fill="#f3a84b" color="#f3a84b"/> {wash.rating}</div></div><div className="tags">{wash.tags.map(t=><span key={t}>{t}</span>)}<span className="reviews">{wash.reviews} ta baho</span></div><div className="card-bottom"><div><small>Yuvish narxi</small><strong>{wash.price} <small>so‘mdan</small></strong></div><button className="book-btn" onClick={()=>onBook(wash)}>Bron qilish <ArrowRight size={15}/></button></div></div></article>}

function SectionTitle({onAll}){return <div className="section-title"><div><span className="section-kicker">SIZGA YAQIN</span><h2>Ommabop avtomoykalar</h2></div><button className="see-all" onClick={onAll}>Barchasini ko‘rish <ArrowRight size={16}/></button></div>}
function Home({onExplore,onBook}){return <><Hero onExplore={onExplore}/><main className="main"><SectionTitle onAll={onExplore}/><div className="filter-row"><button className="filter active">Barchasi</button><button className="filter"><Star size={14}/> Eng yuqori reyting</button><button className="filter"><Clock3 size={14}/> Hozir ochiq</button><button className="filter"><SlidersHorizontal size={14}/> Filtrlar</button></div><div className="cards">{washes.map(w=><WashCard key={w.id} wash={w} onBook={onBook}/>)}</div><div className="promo"><div><span className="promo-label">WASHMEE CLUB</span><h2>Har oy ko‘proq tejang.</h2><p>Obuna bo‘ling va har bir yuvishda 20% gacha chegirmaga ega bo‘ling.</p><button className="dark-btn">Tariflarni ko‘rish <ArrowRight size={16}/></button></div><div className="promo-art"><div className="bubble b1">20%</div><div className="bubble b2">−</div><div className="car-shape"><CarFront size={100}/></div></div></div></main></>}

function Explore({onBook}){const [query,setQuery]=useState('');const filtered=washes.filter(w=>w.name.toLowerCase().includes(query.toLowerCase())||w.area.toLowerCase().includes(query.toLowerCase()));return <main className="main explore"><div className="explore-head"><div><span className="section-kicker">TAJRIBA QILING</span><h1>O‘zingizga mos avtomoykani toping</h1><p>Toshkentdagi eng yaxshi avtomoykalar — bir joyda.</p></div><div className="searchbox"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nom yoki manzil bo‘yicha qidirish..."/><button><SlidersHorizontal size={17}/> Filtr</button></div></div><div className="explore-layout"><div className="map-panel"><div className="map-label"><MapPin size={16}/> Toshkent</div>{washes.map((w,i)=><button key={w.id} className={'map-dot md'+i} onClick={()=>onBook(w)}><span>{w.price}</span></button>)}<div className="map-you"><Navigation size={17} fill="white"/></div></div><div className="result-list"><div className="result-top"><b>{filtered.length} ta avtomoyka topildi</b><button>Masofa bo‘yicha <ChevronDown size={14}/></button></div>{filtered.map(w=><WashCard key={w.id} wash={w} onBook={onBook}/>)}</div></div></main>}

function BookingModal({wash,onClose,onDone}){const [time,setTime]=useState(times[2]);const [step,setStep]=useState(1); if(!wash)return null; return <div className="overlay"><div className="modal">{step===1?<><div className="modal-head"><div><span className="section-kicker">TEZKOR BRON</span><h2>{wash.name}</h2><p><MapPin size={14}/> {wash.area} · {wash.distance}</p></div><button className="close" onClick={onClose}><X/></button></div><div className="booking-summary"><img src={wash.image}/><div><b>Yengil avtomobil</b><p>Standart yuvish</p><strong>{wash.price} so‘m</strong></div><button className="change">O‘zgartirish</button></div><label className="label">Sanani tanlang</label><div className="dates"><button className="date selected"><b>Bugun</b><small>24 Sen</small></button><button className="date"><b>Ertaga</b><small>25 Sen</small></button><button className="date"><b>Jum</b><small>26 Sen</small></button><button className="date"><b>Shan</b><small>27 Sen</small></button></div><label className="label">Bo‘sh vaqtlar</label><div className="times">{times.map(t=><button className={time===t ? 'time selected' : 'time'} onClick={()=>setTime(t)} key={t}>{t}</button>)}</div><button className="primary full" onClick={()=>setStep(2)}>Bronni tasdiqlash <ArrowRight size={17}/></button><div className="secure"><ShieldCheck size={15}/> Bronni bepul bekor qilish mumkin</div></>:<div className="success"><div className="success-icon"><Check size={38}/></div><span className="section-kicker">TABRIKLAYMIZ</span><h2>Broningiz tayyor!</h2><p>{wash.name} · Bugun, {time}</p><div className="qr"><div className="qr-grid">{Array.from({length:49}).map((_,i)=><i key={i} className={(i*7+i*i)%5<2?'on':''}></i>)}</div><b>WM-240924</b><small>Avtomoykaga kirishda ushbu kodni ko‘rsating</small></div><button className="primary full" onClick={()=>{onDone();onClose()}}>Bronlarimga o‘tish <ArrowRight size={17}/></button></div>}</div></div>}

function Bookings(){return <main className="main bookings"><div className="page-heading"><span className="section-kicker">SIZNING SAFARINGIZ</span><h1>Bronlarim</h1><p>Barcha bronlaringizni shu yerdan boshqaring.</p></div><div className="booking-tabs"><button className="active">Barchasi <span>1</span></button><button>Faol</button><button>O‘tgan</button></div><div className="booking-item"><div className="booking-date"><b>24</b><small>Sen</small></div><div className="booking-info"><div className="booking-status">● TASDIQLANGAN</div><h3>Aqua Shine</h3><p><MapPin size={14}/> Yunusobod, 4-mavze</p><div className="booking-meta"><span><CalendarDays size={15}/> Bugun, 24 sentyabr</span><span><Clock3 size={15}/> 14:30</span><span><CarFront size={15}/> Standart yuvish</span></div></div><div className="booking-code"><small>Bron kodi</small><b>WM-240924</b><button>QR kodni ko‘rsatish <ArrowRight size={14}/></button></div></div></main>}

function App(){const [page,setPage]=useState('home');const [selected,setSelected]=useState(null);const [booked,setBooked]=useState(false);const openBook=w=>setSelected(w);return <><Header setPage={setPage}/>{page==='home'&&<Home onExplore={()=>setPage('explore')} onBook={openBook}/>} {page==='explore'&&<Explore onBook={openBook}/>} {page==='bookings'&&<Bookings/>}<footer><div className="brand"><div className="logo"><span></span><span></span><span></span></div><b>Wash<span>Mee</span></b></div><p>Vaqtingizni qadrlaymiz.</p><span>© 2024 WashMee</span></footer>{selected&&<BookingModal wash={selected} onClose={()=>setSelected(null)} onDone={()=>{setBooked(true);setPage('bookings')}}/>}</>}

createRoot(document.getElementById('root')).render(<App/>);
